OPENROUTER_API_KEY = "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"
ASTRA_DB_ID = "43a82168-253b-4872-92bf-2827c05c6743"
ASTRA_DB_REGION = "us-east"
ASTRA_DB_TOKEN = "AstraCS:UwdFUYKPYZqFGWHqCsEooNmW:be72157709b8a90443501134b7afcf65f84c4f097a1d667bde6dcbba9921e972"
ASTRA_DB_KEYSPACE = "default_keyspace"

# Model-specific OpenRouter API keys
OPENROUTER_KEY_GEMINI = "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"
OPENROUTER_KEY_LLAMA = "your-llama-api-key"
OPENROUTER_KEY_DEEPSEEK = "your-deepseek-api-key"
OPENROUTER_KEY_DOLPHIN = "your-dolphin-api-key"
