OPENROUTER_API_KEY = "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"
ASTRA_DB_ID = "43a82168-253b-4872-92bf-2827c05c6743"
ASTRA_DB_REGION = "us-east"
ASTRA_DB_TOKEN = "AstraCS:jIzZAWkTQcHHiSGGPqdOAvcq:e4ef240c8f2d665baf5e36dc06a1b38848c3dcd5304902cc576663b37406d9a4"
ASTRA_DB_KEYSPACE = "default_keyspace"

# Model-specific OpenRouter API keys
OPENROUTER_KEY_GEMINI = "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"
OPENROUTER_KEY_LLAMA = "your-llama-api-key"
OPENROUTER_KEY_DEEPSEEK = "your-deepseek-api-key"
OPENROUTER_KEY_DOLPHIN = "your-dolphin-api-key"
